[feat]ユーザの修正ページからユーザの削除
NUTFes/chosei-chan pull request #102
Opened 2023-08-15 06:27 UTC by Kubosaka

#101 

resolve #0

# 概要

- ユーザの修正ページで削除ができるようにした。
- 戻るボタンの色の修正

# 画面スクリーンショット等

- `URL`
<img width="196" alt="スクリーンショット 2023-08-15 15 25 18" src="https://github.com/NUTFes/chosei-chan/assets/115447919/5002f686-6f37-4da0-bd83-57ac7404c74b">

# テスト項目

- 修正ページからユーザの削除ができるか確認する

# 備考

2023-08-18 13:26 UTC, imaimai17468 requested changes
動作は問題なし！
ちょっと改良できそうな部分をレビューしました

2023-08-18 13:26 UTC, imaimai17468 commented on src/pages/[scheduleId]/edit.tsx
> +      await router.push('/' + props.id)
したみたいにすると、指定したdynamic routeのqueryに対して正確な値を入れることができるので、ただの文字列の足し算から生まれるバグとか曖昧さを消すことができる、おすすめ
```suggestion
      await router.push({
            pathname: '/[scheduleId]', 
            query: {
                  scheduleId: props.id
            }
      }
)
```

2023-08-18 13:26 UTC, imaimai17468 commented on src/pages/[scheduleId]/edit.tsx
> +      await deleteUser(props.id, users[user_id])
せっかくawait文を使ってるので、できればtry...catchではなく、await...then...catchがいいかな
参考：https://nut-m-e-g.slack.com/archives/C029KG3MAS3/p1691693711905709

2026-07-03 07:57 UTC, hikahana approved these changes
LGTM

2026-07-03 07:58 UTC, merged