[feat]calenderコンポーネントの作成
NUTFes/chosei-chan pull request #22
Opened 2023-07-22 17:16 UTC by harata-t

# 対応Issue

resolve #9

# 概要

- calenderコンポーネントの作成
- date-fnsを使用してカレンダーを作成
- 前の月と次の月に変更する機能の開発
- 複数の日付の選択を可能にした
- 選択した日付のUNIX時間を配列で取得する機能の開発

# 画面スクリーンショット等

- `URL`
スクリーンショット
<img width="1440" alt="スクリーンショット 2023-07-23 2 16 08" src="https://github.com/NUTFes/chosei-chan/assets/107479066/e0b71636-8330-49d5-bef5-d485f479fbc9">

# テスト項目

- [ ] `npm install date-fns` を実行してから、上記のように表示されている
- [ ] 前の月、次の月が正常に動作している
- [ ] 同じ日付を2回押すと選択が解除される（ボタンの色が戻る）
- [ ] 日付を複数選択して、送信ボタンを押すとconsoleに選択した日付のUNIX時間が小さい順で配列に格納されている

# 備考

2023-07-22 18:31 UTC, hikahana reviewed
LGTM!

2023-07-23 04:08 UTC, imaimai17468 requested changes
大筋はOKだと思います！
命名や型の部分で少しレビューしました

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +        <button className='ml-auto text-2xl ' onClick={handleNextMonth}>{getMonth(addMonths(targetDate, 1)) + 1}月 ＞</button>
シングルクォーテーションかダブルクォーテーションは統一しよう
（最新developをpullしてきて、eslintとprettierのVScode拡張機能を入れたら、cmd + sを押すだけで自動整形してくれるようになります）
参考https://ralacode.com/blog/post/vscode-prettier/

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +  const [targetDate, setTargetDate] = useState(new Date());
targetMonthの方が意味は伝わりやすいかも！

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +    const unixTime = date.getTime() / 1000;
ここは別に/1000しなくても大丈夫！

```suggestion
    const unixTime = date.getTime();
```

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +                const unixTime = date.getTime() / 1000;
ここも同様

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +    <div className="grid w-[40%] my-2 mx-auto">
TailwindCSSにおいて`w-[hogehoge]`とか`bg-[#hogehoge]`みたいなオリジナルな値は絶対使っちゃダメ！
そこを自由にしてしまったらデザインがガバガ生まれてなんでもありになってしまうのと、Tailwindの良さがなくなってしまうので
ここは固定値で大丈夫

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +            <th className="py-2">土</th>
配列を作って繰り返し処理にしたらまとめられるよ！
`['日', '月', '火', '水', '木', '金', '土']`は別で宣言しておいてもOK！

```suggestion
           {['日', '月', '火', '水', '木', '金', '土'].map((day) => (
              <th key={day} className="py-2">
                {day}
              </th>
            ))}
```

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +  };
送信処理まで実装してくれてありがとう！
selectedDatesなんだけど、できればCalenderコンポーネントのpropsにonChangeを定義して、そこでselectedDatesを返すようにしたい！
buttonのonClickみたいに使えるようになるのが理想！
```
// トップページ
const [selectedDates, setSelectedDates] = useState<number[]>();
// ~省略~
<Calender onChange={setSelectedDates} />
```

2023-07-23 04:08 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +  const getCalendarArray = (date: number | Date) => {
getCalenderArrayにあたえるtargetDateはDate型で確定しているので、ここはDateのみの許容でいいかな

```suggestion
  const getCalendarArray = (date: Date) => {
```

2023-07-23 17:34 UTC, imaimai17468 requested changes
propsの処理と惜しい部分がいくつかあったのでレビューしました！

2023-07-23 17:34 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.stories.tsx
> +  title: 'common/Calender',
ここってStorybookで表示される名前を決めてるんだけど、Calenderはscreenの中にあるから、名前もそれに合わせて方がいいかな！
```suggestion
  title: 'screen/Calender',
```

2023-07-23 17:34 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +const Calendar: React.FC<CalenderProps> = (onChange) => {
今後propsを増やすことも考えて、objectの要素の一つとして受け取っちゃっていいかな

```suggestion
const Calendar: React.FC<CalenderProps> = ({ onChange }) => {
```

2023-07-23 17:34 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +  }
惜しい！ここでonChangeを使うことで外部からCalenderの値を受け取ることができる！（buttonのonClickみたいに）

```suggestion
  const handleSubmit = () => {
    onChange(selectedDates)
  }
```

その上で、Calender.stories.tsxのDefaultのargにonChangeを与えることで実際に試すことができる

```
export const Default: Story = {
  args: {
    onChange: (selectedDates: number[]) => {
      alert(selectedDates)
    },
  },
}
```

2023-07-23 17:34 UTC, imaimai17468 commented on src/components/screen/Calender/Calender.tsx
> +        </button>
[nits]
`<`, `>`で表してもいいけどちょっとぶっきらぼうな感じがする&react-iconsっていうicon用ライブラリも入れてるのでぜひ見てみて〜
https://react-icons.github.io/react-icons/search?q=next

2023-07-24 05:01 UTC, harata-t commented on src/components/screen/Calender/Calender.stories.tsx
> +  title: 'common/Calender',
修正した
https://github.com/NUTFes/chosei-chan/pull/22/commits/8161d8880e085321dec4babca8ce8ec752513b1f

2023-07-24 05:01 UTC, harata-t commented on src/components/screen/Calender/Calender.tsx
> +const Calendar: React.FC<CalenderProps> = (onChange) => {
修正した
https://github.com/NUTFes/chosei-chan/pull/22/commits/4c143888c3fe8faa81b540ed04bcd36b8dfac5c1

2023-07-24 05:02 UTC, harata-t commented on src/components/screen/Calender/Calender.tsx
> +  }
修正した
https://github.com/NUTFes/chosei-chan/pull/22/commits/1b712ff272e56b96f5d18380131048b88d68d7f5

2023-07-24 05:02 UTC, harata-t commented on src/components/screen/Calender/Calender.tsx
> +        </button>
修正した
https://github.com/NUTFes/chosei-chan/pull/22/commits/94259f515a458c19b65a6ed459e3273c42d22adb

2023-07-24 06:04 UTC, Kubosaka commented
レイアウト変えました。
レビューお願いします。

pc版
<img width="1218" alt="スクリーンショット 2023-07-24 15 02 21" src="https://github.com/NUTFes/chosei-chan/assets/115447919/20220582-67b9-46bc-b2de-882832046499">

sp版
<img width="333" alt="スクリーンショット 2023-07-24 15 02 37" src="https://github.com/NUTFes/chosei-chan/assets/115447919/552b3b8a-0458-487c-bc45-590ecdb95de2">

2023-07-24 06:43 UTC, imaimai17468 approved these changes
LGTM!

2023-07-24 06:43 UTC, merged