[feat]メインページの外観作成
NUTFes/chosei-chan pull request #28
Opened 2023-07-23 12:16 UTC by Kubosaka

resolve #27 

# 概要

- メインページの外観を作成した。
- 機能は未実装
- フッターがabsoluteになっていたため修正した。
- inputフォームが背景と同化して見にくかったためバックグラウンドカラーを白に設定した。
# 画面スクリーンショット等

<img width="815" alt="スクリーンショット 2023-07-23 21 14 31" src="https://github.com/NUTFes/chosei-chan/assets/115447919/1f89f9f6-ed82-4ec1-b27a-71bba02f7b62">

スクリーンショット

# テスト項目

- `localhost:3000`にアクセスし、ページが表示されるか確認する。
- 画面が崩れていないか確認する。
- `/pages/index.js`のコードの確認。

# 備考

2023-07-23 17:48 UTC, imaimai17468 requested changes
大筋は大丈夫だけど、ちょっとレビューしました

**気になってる点**
- メモ入力欄は？
- できればスクロールなしでウィンドウに治ってた方が綺麗に感じる
- タイトルとかメモ欄の例を小さく示せるといいね
- 配置を少し変えてもいいかもね
  - STEP1とかの見出しは左揃えに
  - STEP間にdividerを入れる+アイコンがあってもいい

2023-07-23 17:48 UTC, imaimai17468 commented on src/pages/index.tsx
> +        <Input></Input>
inputはchildrenを持たないので一つにまとめてしまって大丈夫
```suggestion
        <Input />
```

2023-07-23 17:48 UTC, imaimai17468 commented on src/pages/index.tsx
> +        <p className='my-auto flex-wrap text-xl underline'>イベント名を入力</p>
flexを当ててないのにflex-wrap単体を当ててるのは意図があったりする？

2023-07-23 17:48 UTC, imaimai17468 commented on src/pages/index.tsx
> +        <p className='my-auto flex-wrap text-xl underline'>日程の入力</p>
ここも

2023-07-24 06:00 UTC, Kubosaka commented on src/pages/index.tsx
> +        <Input></Input>
[c45fbde]　(https://github.com/NUTFes/chosei-chan/pull/28/commits/c45fbde3ad81436eca3f37e76b46aae22880aed6)修正しました。

2023-07-24 06:01 UTC, Kubosaka commented on src/pages/index.tsx
> +        <p className='my-auto flex-wrap text-xl underline'>イベント名を入力</p>
[942dd9c](https://github.com/NUTFes/chosei-chan/pull/28/commits/942dd9cf42cce93d8450b7ce25d5782b607b018b)　修正しました

2023-07-24 06:01 UTC, Kubosaka commented on src/pages/index.tsx
> +        <p className='my-auto flex-wrap text-xl underline'>日程の入力</p>
[942dd9c](https://github.com/NUTFes/chosei-chan/pull/28/commits/942dd9cf42cce93d8450b7ce25d5782b607b018b)

2023-07-24 06:08 UTC, Kubosaka commented
レイアウト変更しました。
レビューお願いします。
<img width="1218" alt="スクリーンショット 2023-07-24 15 02 21" src="https://github.com/NUTFes/chosei-chan/assets/115447919/25d6533b-5ed9-4995-96ca-72eeaa793c88">

sp版
<img width="333" alt="スクリーンショット 2023-07-24 15 02 37" src="https://github.com/NUTFes/chosei-chan/assets/115447919/a0fc95d8-bb41-4345-b047-8e78ec7a379f">

2023-07-24 07:47 UTC, Kubosaka commented
送ってくれたコードの修正しました。
- sp版用に折り返し
- marginの削除

<img width="1242" alt="スクリーンショット 2023-07-24 16 43 46" src="https://github.com/NUTFes/chosei-chan/assets/115447919/764c2481-120a-45b9-89a2-6ce2586621ee">

sp版
<img width="331" alt="スクリーンショット 2023-07-24 16 44 03" src="https://github.com/NUTFes/chosei-chan/assets/115447919/34f10ff4-7ccd-4a83-b71a-0917d12ad000">

2023-07-24 08:46 UTC, imaimai17468 approved these changes
LGTM!

2023-07-24 08:46 UTC, merged