[feat]shareButtonコンポーネントの作成
NUTFes/chosei-chan pull request #32
Opened 2023-07-24 11:54 UTC by harata-t

# 対応Issue

resolve #23 

# 概要

- ShareButtonコンポーネントの作成
- ページURLのコピーボタンの作成
- URLコピーが成功した場合に、Toast通知が出るようにした
- Line共有ボタンの作成

# 画面スクリーンショット等

- `URL`
スクリーンショット
<img width="1440" alt="スクリーンショット 2023-07-24 20 46 07" src="https://github.com/NUTFes/chosei-chan/assets/107479066/a5da0647-c3f9-40b1-a041-cceaf144388c">

- ログイン前
<img width="1440" alt="スクリーンショット 2023-07-24 20 46 59" src="https://github.com/NUTFes/chosei-chan/assets/107479066/5500355d-cee5-4978-acb5-87c571daa391">

- ログイン後
<img width="1440" alt="スクリーンショット 2023-07-24 20 46 38" src="https://github.com/NUTFes/chosei-chan/assets/107479066/6f9726f1-e1a6-4fac-936d-ce32acf1f73a">

# テスト項目

- `npm install react-toastify` をする
- [ ] 上記のボタンが表示されている
- [ ] コピーボタンをホバーしたら色が少し変わる
- [ ] コピーボタンを押したらURLがコピーされ、通知がくる
- [ ] Line共有ボタンを押したら、共有ページに飛ぶ

# 備考

2023-07-24 12:10 UTC, imaimai17468 requested changes
レビューしました
型定義周りがいらないというのと、デザインがちょっとだけ！

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.type.ts
> +} & JSX.IntrinsicElements['button']
今回特に使ってるPropsはないだろうから、型定義はしなくて大丈夫！

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.tsx
> +const ShareButton: React.FC<ShareButtonProps> = () => {
props特にないならこれでOK
あとButtonが複数あるコンポーネントなので複数形で

```suggestion
const ShareButtons: React.FC = () => {
```

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.tsx
> +      </div>
押す要素であればbuttonで定義しよう

```suggestion
      <button onClick={handleShareLine}>
        <Image src='/LINE_Brand_icon.png' width={36} height={36} alt='logo' />
      </div>
```

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.tsx
> +      </button>
リンクコピーボタンは丸くしちゃっていいんじゃないかと思うのと、gapをちょっとだけつけてもいいと思う

```suggestion
    <div className='flex items-center gap-2'>
      <button className='btn btn-circle btn-ghost' onClick={handleCopy}>
        <AiOutlineCopy size='25' />
      </button>
```

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +  },
propsないならここら辺なしでOK！

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +}
propsがないので中身空でOK
```suggestion
export const Defualt: Story = {}
```

2023-07-24 12:10 UTC, imaimai17468 commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +}
これ以降はpropsがあったときにわかりやすく別々に示すためのものなのでなくて大丈夫

2023-07-25 07:37 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.type.ts
> +} & JSX.IntrinsicElements['button']
[6f5d3d0](https://github.com/NUTFes/chosei-chan/pull/32/commits/6f5d3d058992461d55cda6c817889aa08c389a69)

2023-07-25 07:37 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.tsx
> +const ShareButton: React.FC<ShareButtonProps> = () => {
[73b81df](https://github.com/NUTFes/chosei-chan/pull/32/commits/73b81df898afda62ef50c5f30bc200715ae5c8dd)
[21af867](https://github.com/NUTFes/chosei-chan/pull/32/commits/21af867ea7356b2cf786ae4d1f8ae8935a7cdcfc)

2023-07-25 07:38 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +  },
[73b81df](https://github.com/NUTFes/chosei-chan/pull/32/commits/73b81df898afda62ef50c5f30bc200715ae5c8dd)

2023-07-25 07:38 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +}
[73b81df](https://github.com/NUTFes/chosei-chan/pull/32/commits/73b81df898afda62ef50c5f30bc200715ae5c8dd)

2023-07-25 07:38 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.stories.tsx
> +}
[73b81df](https://github.com/NUTFes/chosei-chan/pull/32/commits/73b81df898afda62ef50c5f30bc200715ae5c8dd)

2023-07-25 07:38 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.tsx
> +      </div>
[4731047](https://github.com/NUTFes/chosei-chan/pull/32/commits/4731047719e73480e6d68f2c61400b1e7eea208f)

2023-07-25 07:38 UTC, harata-t commented on src/components/common/ShareButton/ShareButton.tsx
> +      </button>
[d7d8459](https://github.com/NUTFes/chosei-chan/pull/32/commits/d7d845989f510b42d70b9048542acf9bb89e87bf)

2023-07-25 09:57 UTC, imaimai17468 approved these changes
LGTM!

2023-07-25 09:57 UTC, merged